In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("starbucks.csv")
df.head()

,Beverage_category,Beverage,Beverage_prep,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg)
0,Coffee,Brewed Coffee,Short,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0%,0%,0%,0%,175
1,Coffee,Brewed Coffee,Tall,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0%,0%,0%,0%,260
2,Coffee,Brewed Coffee,Grande,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,0%,0%,330
3,Coffee,Brewed Coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,2%,0%,410
4,Classic Espresso Drinks,Caffè Latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10%,0%,20%,0%,75

In [29]:
df.columns

Index(['Beverage_category', 'Beverage', 'Beverage_prep', 'Calories',
       ' Total Fat (g)', 'Trans Fat (g) ', 'Saturated Fat (g)', ' Sodium (mg)',
       ' Total Carbohydrates (g) ', 'Cholesterol (mg)', ' Dietary Fibre (g)',
       ' Sugars (g)', ' Protein (g) ', 'Vitamin A (% DV) ', 'Vitamin C (% DV)',
       ' Calcium (% DV) ', 'Iron (% DV) ', 'Caffeine (mg)'],
      dtype='object')

In [20]:
df.columns
df.shape

(242, 18)

In [22]:
df.isnull().sum()

Beverage_category            0
Beverage                     0
Beverage_prep                0
Calories                     0
 Total Fat (g)               0
Trans Fat (g)                0
Saturated Fat (g)            0
 Sodium (mg)                 0
 Total Carbohydrates (g)     0
Cholesterol (mg)             0
 Dietary Fibre (g)           0
 Sugars (g)                  0
 Protein (g)                 0
Vitamin A (% DV)             0
Vitamin C (% DV)             0
 Calcium (% DV)              0
Iron (% DV)                  0
Caffeine (mg)                1
dtype: int64

In [24]:
df.duplicated().sum()

np.int64(0)

In [32]:
df.head()

,Beverage_category,Beverage,Beverage_prep,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg)
0,Coffee,Brewed Coffee,Short,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0%,0%,0%,0%,175
1,Coffee,Brewed Coffee,Tall,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0%,0%,0%,0%,260
2,Coffee,Brewed Coffee,Grande,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,0%,0%,330
3,Coffee,Brewed Coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,2%,0%,410
4,Classic Espresso Drinks,Caffè Latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10%,0%,20%,0%,75

In [4]:
df['Beverage_category'].nunique()

9

In [36]:
df['Beverage_prep'].nunique()

13

In [37]:
df['Beverage'].nunique()

33

### Create the First Dimension Table

In [5]:
dim_category = df[['Beverage_category']].drop_duplicates().reset_index(drop=True)

dim_category['Category_ID'] = range(1, len(dim_category)+1)

dim_category = dim_category[['Category_ID', 'Beverage_category']]

dim_category

   Category_ID                  Beverage_category
0            1                             Coffee
1            2            Classic Espresso Drinks
2            3          Signature Espresso Drinks
3            4                   Tazo® Tea Drinks
4            5              Shaken Iced Beverages
5            6                          Smoothies
6            7        Frappuccino® Blended Coffee
7            8  Frappuccino® Light Blended Coffee
8            9         Frappuccino® Blended Crème

In [41]:
# df.head()

### Create the 2nd Dimension Table

In [6]:
dim_beverage = df[['Beverage']].drop_duplicates().reset_index(drop=True)  #from that column, duplicates are removed and the index is reset.

dim_beverage['Beverage_ID'] = range(1, len(dim_beverage)+1)  #This creates range(1,34), because here we have 33 unique values, that why it is..!, Beverage_ID becomes surrogate keys.

dim_beverage = dim_beverage[['Beverage_ID', 'Beverage']]    #This just rearranges the columns

dim_beverage

    Beverage_ID                                           Beverage
0             1                                      Brewed Coffee
1             2                                        Caffè Latte
2             3                Caffè Mocha (Without Whipped Cream)
3             4           Vanilla Latte (Or Other Flavoured Latte)
4             5                                    Caffè Americano
5             6                                         Cappuccino
6             7                                           Espresso
7             8                         Skinny Latte (Any Flavour)
8             9                                  Caramel Macchiato
9            10      White Chocolate Mocha (Without Whipped Cream)
10           11              Hot Chocolate (Without Whipped Cream)
11           12        Caramel Apple Spice (Without Whipped Cream)
12           13                                          Tazo® Tea
13           14                               Tazo® Chai Tea Latte
14           15                              Tazo® Green Tea Latte
15           16                          Tazo® Full-Leaf Tea Latte
16           17    Tazo® Full-Leaf Red Tea Latte (Vanilla Rooibos)
17           18            Iced Brewed Coffee (With Classic Syrup)
18           19     Iced Brewed Coffee (With Milk & Classic Syrup)
19           20         Shaken Iced Tazo® Tea (With Classic Syrup)
20           21  Shaken Iced Tazo® Tea Lemonade (With Classic S...
21           22                          Banana Chocolate Smoothie
22           23                       Orange Mango Banana Smoothie
23           24                         Strawberry Banana Smoothie
24           25                                             Coffee
25           26                      Mocha (Without Whipped Cream)
26           27                    Caramel (Without Whipped Cream)
27           28                  Java Chip (Without Whipped Cream)
28           29                                              Mocha
29           30                                            Caramel
30           31                                          Java Chip
31           32       Strawberries & Crème (Without Whipped Cream)
32           33               Vanilla Bean (Without Whipped Cream)

### Create 3rd Dimention table

In [7]:
dim_prep = df[['Beverage_prep']].drop_duplicates().reset_index(drop=True)

dim_prep['Prep_ID'] = range(1, len(dim_prep)+1)

dim_prep = dim_prep[['Prep_ID', 'Beverage_prep']]

dim_prep

    Prep_ID       Beverage_prep
0         1               Short
1         2                Tall
2         3              Grande
3         4               Venti
4         5   Short Nonfat Milk
5         6             2% Milk
6         7             Soymilk
7         8    Tall Nonfat Milk
8         9  Grande Nonfat Milk
9        10   Venti Nonfat Milk
10       11                Solo
11       12              Doppio
12       13          Whole Milk

In [45]:
df.head()

,Beverage_category,Beverage,Beverage_prep,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg)
0,Coffee,Brewed Coffee,Short,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0%,0%,0%,0%,175
1,Coffee,Brewed Coffee,Tall,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0%,0%,0%,0%,260
2,Coffee,Brewed Coffee,Grande,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,0%,0%,330
3,Coffee,Brewed Coffee,Venti,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,2%,0%,410
4,Classic Espresso Drinks,Caffè Latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10%,0%,20%,0%,75

# Create a FACT Table

In [8]:
fact_nutrition = df.merge(
    dim_category,
    on='Beverage_category',
    how='left'
)

fact_nutrition = fact_nutrition.merge(
    dim_beverage,
    on='Beverage',
    how='left'
)

fact_nutrition = fact_nutrition.merge(
    dim_prep,
    on='Beverage_prep',
    how='left'
)

fact_nutrition.head()

,Beverage_category,Beverage,Beverage_prep,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),...,Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg),Category_ID,Beverage_ID,Prep_ID
0,Coffee,Brewed Coffee,Short,3,0.1,0.0,0.0,0,5,0,...,0,0.3,0%,0%,0%,0%,175,1,1,1
1,Coffee,Brewed Coffee,Tall,4,0.1,0.0,0.0,0,10,0,...,0,0.5,0%,0%,0%,0%,260,1,1,2
2,Coffee,Brewed Coffee,Grande,5,0.1,0.0,0.0,0,10,0,...,0,1.0,0%,0%,0%,0%,330,1,1,3
3,Coffee,Brewed Coffee,Venti,5,0.1,0.0,0.0,0,10,0,...,0,1.0,0%,0%,2%,0%,410,1,1,4
4,Classic Espresso Drinks,Caffè Latte,Short Nonfat Milk,70,0.1,0.1,0.0,5,75,10,...,9,6.0,10%,0%,20%,0%,75,2,2,5

In [9]:
fact_nutrition = fact_nutrition.drop(
    columns=[
        'Beverage_category',
        'Beverage',
        'Beverage_prep'
    ]
)

fact_nutrition.head()

,Calories,Total Fat (g),Trans Fat (g),Saturated Fat (g),Sodium (mg),Total Carbohydrates (g),Cholesterol (mg),Dietary Fibre (g),Sugars (g),Protein (g),Vitamin A (% DV),Vitamin C (% DV),Calcium (% DV),Iron (% DV),Caffeine (mg),Category_ID,Beverage_ID,Prep_ID
0,3,0.1,0.0,0.0,0,5,0,0,0,0.3,0%,0%,0%,0%,175,1,1,1
1,4,0.1,0.0,0.0,0,10,0,0,0,0.5,0%,0%,0%,0%,260,1,1,2
2,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,0%,0%,330,1,1,3
3,5,0.1,0.0,0.0,0,10,0,0,0,1.0,0%,0%,2%,0%,410,1,1,4
4,70,0.1,0.1,0.0,5,75,10,0,9,6.0,10%,0%,20%,0%,75,2,2,5

# Built a STAR Scheme

In [10]:
fact_nutrition.columns

Index(['Calories', ' Total Fat (g)', 'Trans Fat (g) ', 'Saturated Fat (g)',
       ' Sodium (mg)', ' Total Carbohydrates (g) ', 'Cholesterol (mg)',
       ' Dietary Fibre (g)', ' Sugars (g)', ' Protein (g) ',
       'Vitamin A (% DV) ', 'Vitamin C (% DV)', ' Calcium (% DV) ',
       'Iron (% DV) ', 'Caffeine (mg)', 'Category_ID', 'Beverage_ID',
       'Prep_ID'],
      dtype='object')

In [2]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [13]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Suraj$80@localhost/STARBUCKS"
)

print("Connection Created")

Connection Created

In [14]:
dim_category.to_sql(
    name='dim_category',
    con=engine,
    if_exists='replace',
    index=False
)

print("dim_category loaded successfully")

dim_category loaded successfully

In [17]:
dim_beverage.to_sql(
    name = 'dim_beverage',
    con=engine,
    if_exists='replace',
    index = False
)

print('dim_beverage loaded successfully')

dim_beverage loaded successfully

In [18]:
dim_prep.to_sql(
    name='dim_prep',
    con=engine,
    if_exists='replace',
    index=False
)

print("dim_prep loaded")

dim_prep loaded

LOAD FACT TABLE

In [20]:
fact_nutrition.columns.tolist()

['Calories',
 ' Total Fat (g)',
 'Trans Fat (g) ',
 'Saturated Fat (g)',
 ' Sodium (mg)',
 ' Total Carbohydrates (g) ',
 'Cholesterol (mg)',
 ' Dietary Fibre (g)',
 ' Sugars (g)',
 ' Protein (g) ',
 'Vitamin A (% DV) ',
 'Vitamin C (% DV)',
 ' Calcium (% DV) ',
 'Iron (% DV) ',
 'Caffeine (mg)',
 'Category_ID',
 'Beverage_ID',
 'Prep_ID']

In [22]:
fact_nutrition.to_sql(
    name='fact_nutrition',
    con=engine,
    if_exists='replace',
    index=False
)

print("fact_nutrition loaded")

fact_nutrition loaded

In [21]:
fact_nutrition.columns = (
    fact_nutrition.columns
    .str.strip()                # remove leading/trailing spaces
    .str.replace(' ', '_')
    .str.replace('(', '', regex=False)
    .str.replace(')', '', regex=False)
    .str.replace('%', 'Percent', regex=False)
    .str.replace('/', '_', regex=False)
)

fact_nutrition.columns

Index(['Calories', 'Total_Fat_g', 'Trans_Fat_g', 'Saturated_Fat_g',
       'Sodium_mg', 'Total_Carbohydrates_g', 'Cholesterol_mg',
       'Dietary_Fibre_g', 'Sugars_g', 'Protein_g', 'Vitamin_A_Percent_DV',
       'Vitamin_C_Percent_DV', 'Calcium_Percent_DV', 'Iron_Percent_DV',
       'Caffeine_mg', 'Category_ID', 'Beverage_ID', 'Prep_ID'],
      dtype='object')